#!/bin/bash

case "$1" in
    cleanbuild)
        $0 clean
        $0 build
        ;;
	clean)
	    rm -rf bin -f src/*.class
		;;
	build)
	    if [ ! -d bin ]; then
	       mkdir bin
	    fi
	    javac -d bin -cp src:lib/BreezySwing.jar src/*.java
		;;
	run)
	    java -cp lib/BreezySwing.jar:bin InheritanceAndInterfacesApplication
		;;
	run-debug)
	    java -cp lib/BreezySwing.jar:bin InheritanceAndInterfacesApplication debug
	    	;;
	*)
	    echo "usage: $0 { clean | build | run }"
		;;
esac

exit

